# Generated by Django 4.2.5 on 2023-09-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghumo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
